
          
spring:        
  datasource:
    url: jdbc:mysql://localhost:3306/dbtest
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
server:
  port: 8090 
